### PR TITLE
Fixes #19 model.md added

### LINKED ISSUE #19: [Bug] No model and api related directory
**Describe the bug**
Since we are using dynamodb as a database, and we have a pretty complex/confusing key schema due to PK and SK related stuff. Hence I suggest creating a separate API directory that will be storing API-related information like endpoints, various models, integration mapping templates, etc.

### PR DESCRIPTION
**Pull request by danishjamal104**
closes #19 

Added below mentioned models in `API/model.md` file
1. User
2. File
3. Url

Screenshot 2021-04-12 at 6 44 43 PM

### CODE REVIEW

**Comment by danishjamal104** [comment]
@ayush0x00 @lakshya-20 @chhavituteja, any update on review??

**Comment by danishjamal104** [comment]
since we are using `AWS-Cognito` for authenticating users, we don't need to store the hashed passwords in the User model, hence I am updating it in this PR only.

**Comment by lakshya-20** [comment]
> @ayush0x00 @lakshya-20 @chhavituteja, any update on review??

Should we add "u_" and "f_" prefixes before user and file attributes respectively? Else LGTM

**Comment by danishjamal104** [comment]
> > @ayush0x00 @lakshya-20 @chhavituteja, any update on review??
> 
> Should we add "u_" and "f_" prefixes before user and file attributes respectively? Else LGTM

user model will have all the attributes related user only so need to add a prefix

**Review by ayush0x00 — APPROVED** [review]
lgtm

**Review by lakshya-20 — APPROVED** [review]

**Pull request merged**
